name: 'Latex Builder'
description: 'Build a makefile project using a dockerized latex'
inputs:
    build-target:
        description: 'The target to build using make'
        required: true
        default: 'main.pdf'
runs:
    using: 'docker'
    image: 'docker://aliaume/texbuilder:latest'
    args:
        - ${{ inputs.build-target }}


